version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.0  # you can adjust Node version if needed

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Build Next.js app with OpenNext
          command: npm run build

      - run:
          name: Deploy to AWS with SST
          command: npx sst deploy --stage production

workflows:
  version: 2
  deploy_flow:
    jobs:
      - build-and-deploy
