version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.5.0

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Next.js build
          command: npm run build

      - run:
          name: OpenNext build
          command: npm run open-build

      - run:
          name: Deploy to AWS with SST
          command: npm run deploy

workflows:
  version: 2
  deploy_flow:
    jobs:
      - build-and-deploy
